#ifndef INC_DEFINES_H_
#define INC_DEFINES_H_

#define FS 46875.0f

#define SAMPLES 1024
#define FFT_SIZE SAMPLES
#define BUFF_SIZE (2 * SAMPLES)

#define MIC_SENSITIVITY_DBFS (-26.0f)
#define MIC_REFERENCE_LEVEL_DBSPL 94.0f
#define MIC_DBFS_TO_DBSPL (MIC_REFERENCE_LEVEL_DBSPL - MIC_SENSITIVITY_DBFS)
#define CALIBRATION_OFFSET 95.0f

#endif /* INC_DEFINES_H_ */
