/**
 * @file sd_driver.h
 *
 * @brief FatFs disk I/O interface for the SD SPI driver.
 *
 * @details Declares the low-level disk functions required by FatFs
 * 			(disk_initialize, disk_status, disk_read, disk_write,
 * 			disk_ioctl), implemented in sd_driver.c on top of the SD SPI
 * 			driver (sd_spi.h/.c). These functions are wrapped into a
 * 			Diskio_drvTypedef descriptor (SD_Driver) and registered with
 * 			FatFs via FATFS_LinkDriver().
 */

#ifndef INC_SD_DRIVER_H_
#define INC_SD_DRIVER_H_

#include "ff_gen_drv.h"
#include "main.h"

/**
 * @brief SPI4 peripheral handle, generated by STM32CubeMX (spi.c).
 *
 * Shared with the SPI driver: SD_disk_init() passes this handle to
 * SD_Init(), and reconfigures its BaudRatePrescaler after a successful
 * card initialization to raise the clock from the initialiation-safe
 * frequency to the target operating frequency.
 */
extern SPI_HandleTypeDef hspi4;

/**
 * @brief	FatFs driver descriptor for the SD SPI driver, registered with
 * 			FatFs via FATFS_LinkDriver() in fatfs.c.
 */
extern Diskio_drvTypeDef SD_Driver;

/**
 * @brief Initializes the physical disk (FatFs disk_initialize callback).
 *
 * Initializes the SD card over SPI at a low, initialization-safe clock
 * frequency, then reconfigures the SPI peripheral to its target operating
 * clock before returning.
 *
 * @param[in] pdrv Physical drive number (unused; single-volume driver).
 *
 * @return 	Resulting disk status: 0 if initialization succeeded,
 * 			STA_NOINIT otherwise.
 */
DSTATUS SD_disk_init(BYTE pdrv);

/**
 * @brief Returns the current disk status (FatFs disk_status callback).
 *
 * @param[in] pdrv Physical drive number (unused; single-volume driver).
 *
 * @return Current DSTATUS value.
 */
DSTATUS SD_disk_status(BYTE pdrv);

/**
 * @brief Reads one or more 512-byte sectors (FatFs disk_read callback).
 *
 * @param[in] pdrv		Physical drive number (unused; single-volume driver).
 * @param[out] buf		Destination buffer, at least (count * 512) bytes.
 * @param[in] sector	Starting sector (block) address.
 * @param[in] count		Number of consecutive sectors to read.
 *
 * @return	RES_OK on success, RES_NOTRDY if the disk is not initialized,
 * 			RES_ERROR if any block read fails.
 */
DRESULT SD_disk_read(BYTE pdrv, BYTE *buf, DWORD sector, UINT count);

/**
 * @brief Writes one or more 512-byte sectors (FatFs disk_write callback).
 *
 * @param[in] pdrv		Physical drive number (unused; single-volume driver).
 * @param[in] buf		Source buffer, at least (count * 512) bytes.
 * @param[in] sector	Starting sector (block) address.
 * @param[in] count		Number of consecutive sectors to read.
 *
 * @return	RES_OK on success, RES_NOTRDY if the disk is not initialized,
 * 			RES_ERROR if any block write fails.
 */
DRESULT SD_disk_write(BYTE pdrv, const BYTE *buf, DWORD sector, UINT count);

/**
 * @brief Handles miscellaneous disk control requests (FatFs disk_ioctl callback).
 *
 * @param[in] pdrv		Physical drive number (unused; single-volume driver).
 * @param[in] cmd		Control command code (see FatFs diskio.h). Only the
 * 						generic commands used by FatFs itself ale handled
 * 						here (CTRL_SYNC, GET_SECTOR_SIZE, GET_BLOCK_SIZE,
 * 						GET_SECTOR_COUNT); MMC/SDC- and ATA-specific
 * 						commands are not supported.
 * @param[in,out] buf	Command-specific parameter/result buffer.
 *
 * @return RES_OK if the command was handled, RES_PARERR otherwise.
 */
DRESULT SD_disk_ioctl(BYTE pdrv, BYTE cmd, void *buf);

#endif /* INC_SD_DRIVER_H_ */
